version: "3.3"
networks:
  geo:

services:
  geoguess:
    image: geoguess:latest
    ports:
      - target: 5000
        published: 5000
        mode: host
    volumes:
      - type: bind
        source: ./geo/
        target: /geo/
    networks:
      geo:
        aliases:
        - geoguess
    environment:
    - "PYTHONUNBUFFERED=0"
    restart: on-failure
